# Generated by Django 6.1.1 on 2026-09-27 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_exam_examresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttype',
            name='category',
            field=models.CharField(choices=[('coursework', 'Continuous Assessment'), ('exam', 'End of Term Examination')], default='coursework', help_text='Determines if this contributes to Continuous Assessment or End of Term weight pool', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='name',
            field=models.CharField(help_text='e.g., Mid-Term Quiz, Assignment, Final Paper', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='weight_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Weight contribution towards its respective category pool', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum possible marks for this report card score', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, help_text='Final compiled marks scored by the student', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
