# Generated by Django 6.1.1 on 2026-10-01 08:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_exam_unique_together_alter_exam_term'),
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubjectenrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='academics.subject'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g., Chapter 3 Algebra Quiz', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions or details for the students', null=True)),
                ('kind', models.CharField(choices=[('QUIZ', 'Quiz'), ('HOMEWORK', 'Homework'), ('PROJECT', 'Project'), ('OTHER', 'Other Task')], default='HOMEWORK', help_text='Type of student task (Quiz, Homework, Project)', max_length=20)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum achievable marks', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateTimeField(help_text='Submission deadline')),
                ('quiz_data', models.JSONField(blank=True, default=list, help_text='Optional structural JSON for online quiz items', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to='accounts.teacherprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.school')),
                ('subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subjectassignment')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, help_text='Student text answer or submission notes', null=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='assessment_submissions/')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded for this submission', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, help_text="Teacher's comments/feedback", null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('LATE', 'Submitted Late')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assessment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='accounts.teacherprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assessment', 'student')},
            },
        ),
    ]
